name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: "splaa1977"
          key: ${{ secrets.SSHKEY }}
        with:
          rm: true
          source: "."
          target: "/var/www/api.splx.site/"


      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: "splaa1977"
          key: ${{ secrets.SSHKEY }}
          script: cat /opt/app/README.md
