# Build your static website with Eleventy
name: scp files
on: [ push ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          script: |
            cp ~/sites/blog.splx.site/.env /var/www/api.splx.site/.env
            cd /var/www/api.splx.site
            composer install --optimize-autoloader --no-dev

#            php artisan optimize