# Build your static website with Eleventy
name: Deploy
on: [ push ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          overwrite: true
          source: "."
          target: "/var/www/api.splx.site"
      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          debug: true
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          script: cat /var/www/api.splx.site/README.md