# Build your static website with Eleventy
name: scp files
on: [ push ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 46.219.56.21
          username: splx
          password: splaa1977
          port: ${{ secrets.PORT }}
          source: "/"
          target: "/var/www/api.splx.site"