# Build your static website with Eleventy
name: scp files
on: [ push ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 46.219.56.21
          username: splx
          password: splaa1977
          port: ${{ secrets.PORT }}
          overwrite: true
          source: "./"
          target: "/var/www/api.splx.site"
      - name: Executing remote  command
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USERNAME }}
            PORT: ${{ secrets.PORT }}
            KEY: ${{ secrets.SSH_KEY }}
            script: cat /var/www/api.splx.site/README.md